server:
  port: 8087

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8084
          predicates:
            - Path=/user/**
        - id: order-service
          uri: http://localhost:8085
          predicates:
            - Path=/costumer/**
        - id: order-service
          uri: http://localhost:8086
          predicates:
            - Path=/order/**
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/product/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
